language: cpp

os:
  - linux
  - osx

branches:
  only:
    - develop
    - master
    - testing

env:
  matrix:
    - CONFIG=release
    #- CONFIG=debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - cd ./tests
  - qmake DEFINES+=INTEGRATION_TESTS && make -s -j 2
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
           ./../bin/tests/tests -platform minimal -txt
        && sudo pip install cpp-coveralls
        && coveralls -b `pwd`/unit_tests/ -r `readlink -m ./../` -e tests/ -E .+/moc_.* -E .+/qrc_.* -E .+/qxt.* -E .+/ui_.*  > coveralls.log
        ;
    else
         ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
      ;
    fi

notifications:
  recipients:
    - developer@bekerle.com
  email:
    on_success: change
    on_failure: change
